### ISSUE TITLE
Track order changes in `hasMany`

### ISSUE THREAD

**Issue by denzo** [danielspaniel/ember-data-change-tracker#14]
Firstly, this addon is extremely helpful! Thanks a million!

We ran into a situation where `hasMany` relationship items are reordered. However, the change is not recognised. I believe this is due to sorting prior to comparing arrays' items:
https://github.com/danielspaniel/ember-data-change-tracker/blob/master/addon/utilities.js#L62

We believe that the above use case is rather common when users need to reorder a list of items.

What are the advantages for sorting before comparing and is it substantial enough to outweigh the above use case?

**Comment by danielspaniel** [comment]
Hmm .. boy @denzo you make an interesting point. 
 I never thought that there would be a case where hasMany items would be considered changed based on the position in the hasMany. 
 When you reorder though, the property "position" ( or whatever you call it ) will change, but the actual order that is in the hasMany should not matter, since you are sorting by position anyway to get your sorted order. 
 So, in short, yes, sorting makes comparison way faster. 
And I think what is happening is that you are wanting to have the hasMany recognize changes in the properties of the hasMany items ( like position in your case ), but change tracker does not do that. 
 That is a more involved feature that I backed off on a while ago because I could not figure out an easy to use API for it ( even though I could code it )

**Comment by denzo** [comment]
@danielspaniel Thank you for the quick response.

I agree that having a "position" attribute on each item is a common approach to persisting the order of items. It also, totally makes sense to not to track property changes for performance reasons.

In our case, however, our API stores all the items in an array like field in a NOSQL type database. Therefore, the order of the items on client needs to match the order of the items in the database.

This is my understanding of tracking changes of "hasMany":
1. An item has been added or removed. `didChange = one.length !== other.length`
2. An item has been replaced at a specific index. `didChange = one[i] !== other[i]`

This only my opinion (it doesn't take into account "polymorphic" relationships as I've never had a chance to explore them and my knowledge on them is very limited):

```Sorting items prior to comparing **only** addresses the situation where content of "hasMany" changed order but the items are the same. At the point of writing I could not come up with a use case where a developer would change the order of "hasMany" items and not expect for it to be marked as `didChange = true`.```

I'd like to highlight that in a situation when an item has been replaced at a specific index (point 2 above), sorting prior to comparing does not make it faster as there's no guarantee that the replaced item isn't last.

I do believe, objectively, that the reason for sorting prior to comparing is not very strong.

Would love to hear your thoughts @danielspaniel as I might be missing some crucial points.

**Comment by danielspaniel** [comment]
I think your right @denzo.
 Very well laid out argument. So well, that I realized that I was 100% wrong about sorting being faster in this case, because as you say, even unsorted, your checking array speed will be O(n) linear since you ( after checking length ) just go through the items 1 .. n as you said one[n] === other[n]  .. not really rocket science there.   
 I think I was originally thinking: 
 ```People would NOT want to consider that the hasMany changed if the position in the array changed. Not sure why I thought that .. but ?? as you say .. can't think of that case anymore```
 So, if you want to change the code in function

```javascript
export const hasManyChanged = function(one, other, polymorphic) {
  if (isEmpty(one) && isEmpty(other)) {
    return false;
  }

  if ((one && one.length) !== (other && other.length)) {
    return true;
  }

  if (polymorphic) {
    one = Ember.A(one).sortBy('id');
    other = Ember.A(other).sortBy('id');
    for (let i = 0, len = one.length; i < len; i++) {
      if (serializedModelChanged(one[i], other[i])) {
        return true;
      }
    }
    return false;
  }

  one.sort();
  other.sort();
  for (let i = 0, len = one.length; i < len; i++) {
    if (one[i] !== other[i]) {
      return true;
    }
  }
};
```

and submit a PR, let me know, otherwise I will do it. 

Also, you could ( just as a thought ) use model fragments to store these "unstructured data" models. , which would make this a hasMany fragmentArray ... 
 
But either way .. seems like the hasManyChanged method can be super simplified as you suggest.

**Comment by denzo** [comment]
That's awesome news! I'll whip up a PR tomorrow. 

@danielspaniel Thanks for hearing me out.

**Comment by danielspaniel** [comment]
ok, great @denzo . I just updated the tests on master so you are ready to easily change the code and then change one line in the test that will fail. Should be nice and simple

**Comment by denzo** [comment]
@danielspaniel Here is the promised PR https://github.com/danielspaniel/ember-data-change-tracker/pull/15

Let me know if I missed anything.

**Comment by danielspaniel** [comment]
all set in:
https://github.com/danielspaniel/ember-data-change-tracker/releases/tag/v0.5.5
