### ISSUE TITLE
hasDirtyRelations not working on multiple belongsTo

### ISSUE THREAD

**Issue by arparthasarathi** [danielspaniel/ember-data-change-tracker#44]
I have a model with two **`belongsTo`** attribute. When a change the first belongsTo relation, **`hasDirtyRelations`** is triggered perfectly but on changing the second one, I get false for **`hasDirtyRelations.`**

```qualification.js```
```
export default DS.Model.extend(Validations, {
  profile: DS.belongsTo('profile'),
  degree: DS.belongsTo('degree')
});
```
```profile.js```
```
export default DS.Model.extend({
  name: DS.attr('string'),
  country: DS.attr('string'),
  qualifications: DS.hasMany('qualification')
});
```

```degree.js```
```
export default DS.Model.extend({
  name: DS.attr('string'),
  type: DS.attr('string'),
  country: DS.attr('string')
});
```

```Serializer```
```
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
   profile: { embedded: 'always' },
   degree: { embedded: 'always' }
  }
});
```

The relationships are established perfectly in both the cases for `profile` and `degree` and I could able to retrieve values from both the models. But if any value gets changed in `degree` model, `qualification.get('hasDirtyRelations')` returns `false` while the same returns `true` if there is any change in `profile` data. Is there anything that am missing out? The configs are enabled in the environment

**Comment by danielspaniel** [comment]
That is really odd @arparthasarathi , because change tracker does not support nested dirty tracking. 
 So, the hasDirtyRelations should be false both times ( when you change properties in a belongs to relation ) 
 hasDirtyRelation should only be true in qualification if you replace the belongsTo with another degree or profile  or you remove the profile or degree ( make them null ) 
 Does that make sense?  
 There have been others expressing interest in making in possible to do nested dirtyness ( but not sure you need that ) 
 I think you are just saying .. hey .. qualifications should not  'hasDirtyRelations' if you change a property on the belongsTo
  if that is what you are saying .. then it would help me if you could make a test ( for the repo ) and show in a test that this is happening .. so i can see the issue ( you might have a particular setup that triggers it ) and then i can fix it

**Comment by arparthasarathi** [comment]
Thanks for pointing out @danielspaniel that the nested properties won't affect the output of `hasDIrtyRelations`. 

The mistake was on my part, that I reassigned the whole `profile` object in the `belongsTo` that made `hasDirtyRelations` to return `true`. But was playing with the properties of `degree`.

Thank you for your prompt response. Let me give it a try. Closing this issue for now and shall reopen it if any issues persist.
