### ISSUE TITLE
Object type not tracked properly on creating new record

### ISSUE THREAD

**Issue by arparthasarathi** [danielspaniel/ember-data-change-tracker#46]
I have an object type attribute in my model. I am creating a new record and the data is saved to the back. Now when I try to edit the data, change any of the keys in the object type and discard the changes. But the values of the object type is not rolled back properly. This occurs only when I create a new record. But not when I reload the entire page and get the data from the backend. Below is my model.

`model.js`
```
export default DS.Model.extend(Validations, {
  start_year: DS.attr('string'),
  end_year: DS.attr('string'),
  created_at: DS.attr('datetime'),
  academic_degree: DS.attr('', {defaultValue() {return {};}}),
});
```

**Comment by danielspaniel** [comment]
Can you show how you are changing the object data. Better yet, can you make a PR with a test that shows what you are doing ( and therefore might fail ) so that I can see what is going wrong for you and show you how to fix it ( or fix the change tracker )

**Comment by arparthasarathi** [comment]
To be frank, I am really unaware of writing a test case. It would surely take a hell of time if I need to get versed and create a test case. But I am in an emergency situation to find out a solution for this. I am changing the keys of the object attribute through [ember-power-select](https://ember-power-select.com/). Below is an example for the same. I have put up this [ember-power-select](https://ember-power-select.com/) in a modal and when I close the modal without saving the changes, I rollback the changes made. But the keys inside the object attribute doesn't get rolled back.

`component.js`
```
 <label>Degree</label>
{{#power-select
     search=(action "academicDegree" hpqualification)
     placeholder="Select degree"
     disabled=setDegreeDisable
     selected=hpqualification.academic_degree.name
     onchange=(action (mut hpqualification.academic_degree.name))
     renderInPlace=true
 as |repo|
}}
 {{repo}}
{{/power-select}}
```

I am depicting the flow in a series of screenshots

1) This is the create  form in the modal. The third drop down is dependent on the first two dropdowns.

![image](https://user-images.githubusercontent.com/5359707/39193349-f9751574-47f8-11e8-96a1-f95a9c2d578d.png)

2) View after the record has been created.

![image](https://user-images.githubusercontent.com/5359707/39193362-02c22144-47f9-11e8-9856-e9d7786ad52c.png)

3) This is the view of the edit window containing the modal, where I clear the first dropdown

![image](https://user-images.githubusercontent.com/5359707/39193373-07b5b256-47f9-11e8-8473-15d8b670d8c0.png)

4) On closing the modal, I rollback the attributes, but as you could see the values doesn't get rolledback

![image](https://user-images.githubusercontent.com/5359707/39193382-0dc4aad0-47f9-11e8-89ca-ab6cdfcb4245.png)

Kindly take a look at these and do if anything possible. Or if test cases are required do let me know so that I could spend 2-3 days of time in getting to know and create test cases.

**Comment by danielspaniel** [comment]
This is interesting problem. In a sense your test is right there. You have a model with certain object type attribute and you modify with power select, and it wont roll back.  Do you have auto track enabled in the enviroment ? because i don't see that  hpqualification model using the changeTracker declaration.  So a model has to declare like this: 
export default Model.extend({
  changeTracker: {auto: true},

or 
 you have to set things like this in environment 
// file config/environment.js
var ENV = {
  modulePrefix: 'dummy',
  environment: environment,
  rootURL: '/',
  locationType: 'auto',
  changeTracker: { auto: true }, 
  EmberENV: {
  ... rest of config

 if you don't have this setup then rollback will not work, unless you use manual mode, where you call model.startTrack() before you start editing ( open the modal dialog in your case ) 
     On Tuesday, April 24, 2018, 10:26:39 AM EDT, Parthasarathi Raghavan <notifications@github.com> wrote:  
 
 
To be frank, I am really unaware of writing a test case. It would surely take a hell of time if I need to get versed and create a test case. But I am in an emergency situation to find out a solution for this. I am changing the keys of the object attribute through ember-power-select. Below is an example for the same. I have put up this ember-power-select in a modal and when I close the modal without saving the changes, I rollback the changes made. But the keys inside the object attribute doesn't get rolled back.

component.js
 <label>Degree</label>
{{#power-select
     search=(action "academicDegree" hpqualification)
     placeholder="Select degree"
     disabled=setDegreeDisable
     selected=hpqualification.academic_degree.name
     onchange=(action (mut hpqualification.academic_degree.name))
     renderInPlace=true
 as |repo|
}}
 {{repo}}
{{/power-select}}

I am depicting the flow in a series of screenshots
   
   - This is the create form in the modal. The third drop down is dependent on the first two dropdowns.


   
   - View after the record has been created.


   
   - This is the view of the edit window containing the modal, where I clear the first dropdown


   
   - On closing the modal, I rollback the attributes, but as you could see the values doesn't get rolledback



Kindly take a look at these and do if anything possible. Or if test cases are required do let me know so that I could spend 2-3 days of time in getting to know and create test cases.

**Comment by arparthasarathi** [comment]
I am pretty sure that the config is set to true because the same works perfectly when I edit a record after the component has been initialised (i.e., once the page is reloaded). But not working for the newly created record.

**Comment by arparthasarathi** [comment]
Hi Daniel, did you get any chance to look up on this issue? I am really stuck up with this one and need to get it resolved. Thanks in advance!

**Comment by danielspaniel** [comment]
Hi @arparthasarathi, I did try and recreate this issue( spent about an hour on it ), but I could not do it. Everything worked fine for me. It must be something special/specific about your setup/addons or how you are setting things up that is different, and since I can not see what you are doing or step through your code, I can not fix it unless you can show this error in a PR or an ember twiddle

**Comment by arparthasarathi** [comment]
Hi @danielspaniel, thanks a lot for your kind efforts. But am not sure how to replicate the same issue in PR or ember-twiddle. Trying it out. Meanwhile, it would be of great help if you could share your code that tried to replicate the bug. So that I can take a look if am missing something. Thanks in advance.

**Comment by danielspaniel** [comment]
I understand you are too busy to make the test cases in a PR, but then maybe I am busy too?  I think your best bet is to fork the repo, make the PR,  and setup the case that fails for you.  OR you can make new ember repo and show it there ( so i can see it on github )  OR you can share your repo with me ( give me access rights )  so i can see the problem right there ( this is pretty much the easiest ) and i am willing to screen share with you to go over the code, but those are the 3 choices for now

**Comment by arparthasarathi** [comment]
I really appreciate your efforts and thanks a lot for that! I am trying to recreate the error and shall get back to you at the earliest. I really feel sorry if it was a trouble for you. Thanks a lot buddy!

**Comment by arparthasarathi** [comment]
Hi @danielspaniel, I could able to figure out and nail down the issue which was mainly due to our mishandling of observers. The issues has been fixed and there isn't anything that needs to be fixed.

Thanks a lot for your timely efforts which really helped us in finding out the issue.
