### ISSUE TITLE
Working with ember-concurrency

### ISSUE THREAD

**Issue by dpigera** [danielspaniel/ember-data-change-tracker#51]
Hello,
Is it possible to get ember-data-change-tracker to work with ember-concurrency?

The main issue I'm having is my route model attempts to load data with:

```
import Route from '@ember/routing/route';
import { task } from 'ember-concurrency';
export default Route.extend({
  model: function (){
    return {
      blog: this.get('blogTask').perform()
    };
  },
  blogTask: task(function *(){
    let blog = yield this.get('store').queryRecord('blog', {today:true});
    return blog;
  });
});
```

And then my template (via ember-concurrency) can render:

```
{{
input
    value=model.blog.value.name
    type="text"
    name="name"
    placeholder="Description"
}}
```

Am I missing something very obvious here?

**Comment by danielspaniel** [comment]
@dpigera  not sure what you are talking about since you are not even showing that you are using change tracker .. just that you have problem with ember concurrency .. me puzzled .. going to close this since it does not seem to relate to change tracker but feel free to open it again if you can show it does or explain more
